#this is my script to align reads to the H. zea genome
#MF 10/29/2018

bowtie2-build-l -f /media/megan/"New Volume"/Hz_PopGen_ddRAD_demult/Bowtie_genome_alignments/GCA_002150865.1_Hzea_1.0_genomic.fna 

cd /media/megan/"New Volume"/Hz_PopGen_ddRAD_demult

#end-to-end alignments with highest sensitivity
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_6_11.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_6_11.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_6_15.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_6_15.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_6_1.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_6_1.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_6_22.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_6_22.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_6_29.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_6_29.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_6_34.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_6_34.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_7_23.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_7_23.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_7_24.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_7_24.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_7_2.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_7_2.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_7_35.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_7_35.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_7_5.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_7_5.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_7_9.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_7_9.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_8_22.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_8_22.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_8_25.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_8_25.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_8_28.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_8_28.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_8_37.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_8_37.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_8_39.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_8_39.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_10.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_10.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_11.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_11.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_13.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_13.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_17.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_17.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_18.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_18.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_20.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_20.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_21.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_21.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_22.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_22.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_23.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_23.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_24.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_24.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_25.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_25.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_26.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_26.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_27.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_27.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_28.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_28.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_29.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_29.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_30.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_30.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_31.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_31.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_32.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_32.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_33.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_33.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_34.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_34.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_35.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_35.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_36.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_36.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_37.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_37.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_38.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_38.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_5.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_5.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_6.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_6.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_7.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_7.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_8.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_8.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_early_9.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_early_9.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_18.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_18.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_18_rep.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_18_rep.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_1.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_1.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_21.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_21.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_22.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_22.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_23.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_23.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_23_rep.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_23_rep.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_24.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_24.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_26.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_26.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_28.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_28.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_29.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_29.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_2.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_2.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_30.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_30.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_31.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_31.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_33.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_33.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_34.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_34.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_35.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_35.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_36.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_36.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_37.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_37.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_38.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_38.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_39.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_39.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_40.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_40.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_41.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_41.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_4.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_4.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_5.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_5.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_6.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_6.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_7.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_7.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_8.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_8.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_9.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_9.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2002_late_9_rep.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2002_late_9_rep.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_6_10.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_6_10.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_6_20.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_6_20.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_6_30.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_6_30.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_6_32.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_6_32.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_6_33.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_6_33.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_6_39.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_6_39.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_6_5.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_6_5.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_7_14.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_7_14.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_7_17.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_7_17.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_7_3.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_7_3.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_7_40.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_7_40.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_8_18.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_8_18.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_8_19.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_8_19.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_8_31.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_8_31.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_8_38.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_8_38.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_10.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_10.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_11.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_11.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_12.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_12.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_14.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_14.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_15.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_15.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_20.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_20.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_21.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_21.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_22.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_22.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_23.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_23.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_24.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_24.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_25.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_25.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_26.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_26.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_27.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_27.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_28.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_28.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_29.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_29.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_30.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_30.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_31.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_31.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_32.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_32.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_33.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_33.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_34.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_34.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_35.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_35.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_36.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_36.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_37.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_37.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_38.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_38.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_39.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_39.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_40.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_40.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_8.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_8.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_early_9.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_early_9.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_25.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_25.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_29.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_29.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_30.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_30.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_31.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_31.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_32.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_32.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_34.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_34.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_35.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_35.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_36.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_36.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_40.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_40.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_41.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_41.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_45.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_45.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_46.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_46.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_47.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_47.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_48.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_48.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_49.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_49.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_50.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_50.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_51.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_51.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_52.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_52.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_53.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_53.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_54.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_54.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_55.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_55.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_56.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_56.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_57.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_57.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_58.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_58.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_59.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_59.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_60.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_60.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_61.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_61.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_62.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_62.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2007_late_63.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2007_late_63.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_6_13.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_6_13.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_6_17.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_6_17.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_6_23.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_6_23.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_6_26.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_6_26.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_6_36.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_6_36.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_6_3.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_6_3.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_6_8.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_6_8.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_7_11.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_7_11.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_7_16.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_7_16.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_7_20.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_7_20.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_7_34.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_7_34.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_7_37.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_7_37.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_7_7.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_7_7.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_8_21.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_8_21.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_8_32.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_8_32.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_8_35.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_8_35.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_48.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_48.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_49.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_49.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_50.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_50.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_51.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_51.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_58.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_58.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_59.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_59.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_60.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_60.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_62.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_62.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_63.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_63.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_64.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_64.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_66.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_66.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_67.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_67.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_68.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_68.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_69.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_69.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_70.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_70.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_71.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_71.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_72.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_72.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_73.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_73.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_74.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_74.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_75.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_75.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_76.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_76.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_77.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_77.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_78.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_78.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_79.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_79.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_80.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_80.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_81.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_81.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_82.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_82.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_early_83.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_early_83.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_15.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_15.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_16.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_16.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_19.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_19.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_21.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_21.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_22.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_22.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_24.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_24.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_26.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_26.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_31.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_31.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_32.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_32.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_34.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_34.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_35.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_35.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_37.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_37.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_38.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_38.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_39.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_39.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_40.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_40.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_41.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_41.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_42.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_42.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_43.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_43.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_44.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_44.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_45.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_45.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_46.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_46.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_47.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_47.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_48.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_48.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_49.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_49.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_50.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_50.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_51.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_51.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_52.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_52.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2012_late_53.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2012_late_53.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_12.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_12.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_14.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_14.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_16.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_16.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_18.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_18.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_19.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_19.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_21.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_21.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_24.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_24.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_25.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_25.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_27.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_27.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_28.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_28.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_2.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_2.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_31.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_31.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_35.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_35.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_37.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_37.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_38.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_38.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_40.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_40.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_4.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_4.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_6.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_6.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_7.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_7.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_6_9.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_6_9.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_10.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_10.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_12.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_12.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_13.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_13.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_15.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_15.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_18.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_18.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_19.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_19.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_1.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_1.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_21.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_21.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_22.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_22.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_33.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_33.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_36.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_36.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_38.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_38.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_39.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_39.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_4.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_4.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_6.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_6.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_7_8.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_7_8.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_8_17.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_8_17.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_8_20.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_8_20.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_8_23.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_8_23.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_8_24.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_8_24.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_8_26.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_8_26.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_8_27.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_8_27.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_8_29.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_8_29.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_8_30.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_8_30.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_8_33.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_8_33.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_8_34.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_8_34.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_8_36.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_8_36.sam
bowtie2 -x ./Bowtie_genome_alignments/Hzea_genome/Hzea_genome -U ./AMD_libs1thru8_extended_frags/renamed_samples/HZ_2016_8_40.fq.gz --very-sensitive -S ./Bowtie_genome_alignments/HZ_2016_8_40.sam
