---
output:
  word_document: default
  html_document: default
---
```{r setup, include=FALSE}
library(tidyverse)
library(gridExtra)
library(grid)
theme_set(theme_bw(base_size=10))
theme_update(panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(), 
  plot.title = element_text(hjust = 0.5),
  legend.position = "none")
```

```{r}
F0_growth_DD <- read.csv("~/Desktop/UMD/Crosses_Analysis/Raw_Data_Tabs_Crosses/F0_growth_phenotypes_DD.csv")

F0_growth_CL <- read.csv("~/Desktop/UMD/Crosses_Analysis/Raw_Data_Tabs_Crosses/F0_growth_phenotypes_CL.csv")

BAP11A1 <-  read.csv("~/Desktop/UMD/Crosses_Analysis/Raw_Data_Tabs_Crosses/tabs/BV_BA52_P11_BZM_A1_Scored.csv") %>%
  filter(Population != "BENZON", Population != "Benzon")

DEO9A1 <- read.csv("~/Desktop/UMD/Crosses_Analysis/Raw_Data_Tabs_Crosses/tabs/BV_DE107_O9_BZM_A1_Scored.csv")%>%
  filter(Population != "Benzon", Population != "Benzon")

```

```{r}
F0_growth_DD <- F0_growth_DD %>% 
  mutate(end_weight_mg = end_weight * 1000)

F0_growth_CL <- F0_growth_CL %>% 
  mutate(end_weight_mg = end_weight * 1000)

BAP11A1 <- BAP11A1 %>% 
  mutate(end_weight_mg = Individual.Larvae.Weight * 1000)

DEO9A1 <- DEO9A1 %>% 
  mutate(end_weight_mg = Individual.Larvae.Weight * 1000)
  
F0_growth_DD <- F0_growth_DD %>% 
  mutate(field = case_when(family == "Benzon" ~ "Benzon", TRUE ~ "Field"))

F0_growth_CL <- F0_growth_CL %>% 
  mutate(field = case_when(family == "Benzon" ~ "Benzon", TRUE ~ "Field"))

F0_growth <- rbind(F0_growth_CL, F0_growth_DD)
```



```{r}
 F0_growth_DD %>% filter(end_weight_mg != "") %>%
  group_by(diet_strain, field) %>%
  summarize(
    count = n(),
    mean = mean(end_weight_mg),
    max = max(end_weight_mg),
    min = min(end_weight_mg))
```

```{r}
F0_growth %>%
  filter(end_weight_mg != "") %>%
  group_by(treatment, diet_strain, field) %>%
  summarize(
    count = n(),
    mean = mean(end_weight_mg),
    max = max(end_weight_mg),
    min = min(end_weight_mg))
```

## F2 phenotypes
```{r}
BAP11A1 %>%
filter(end_weight_mg != "") %>%
  group_by(Treatment) %>%
  summarize(
    count = n(),
    mean = mean(end_weight_mg),
    sd = sd(end_weight_mg),
    se = sd/sqrt(n()))
```

```{r}
wilcox.test(BAP11A1$end_weight_mg~BAP11A1$Treatment,paired=FALSE)
```

```{r}
DEO9A1 %>%
filter(end_weight_mg != "") %>%
  group_by(Treatment) %>%
  summarize(
    count = n(),
    mean = mean(end_weight_mg),
    sd = sd(end_weight_mg),
    se = sd/sqrt(n()))

```
```{r}
wilcox.test(DEO9A1$end_weight_mg~DEO9A1$Treatment,paired=FALSE)
```

Mean difference between field and susceptible populations
```{r}
114.27687/21.20792
87.02952/6.31200
```

Founding parents
```{r}
145.6/21.20792
129.5/6.31200
```

```{r}
F0_growth_PDD <-F0_growth_DD %>% filter(diet_strain == "P") %>%
  mutate(log_end_weight = log(end_weight_mg))
F0_growth_ODD <-F0_growth_DD %>% filter(diet_strain == "O") %>%
  mutate(log_end_weight = log(end_weight_mg))
```


```{r}
wilcox.test(F0_growth_ODD$end_weight_mg~F0_growth_ODD$field,paired=FALSE)
wilcox.test(F0_growth_PDD$end_weight_mg~F0_growth_PDD$field,paired=FALSE)
```


```{r}
S6panelA <- F0_growth_DD %>%
  filter(diet_strain == "P",end_weight_mg != "") %>%
  ggplot(aes(x = end_weight_mg, fill = field, alpha = diet_strain)) +
  geom_density(alpha = 0.6) +
  labs(x = "Weight (mg)", y = "Density", tag = "A") +
  scale_fill_manual(name="Population",
                         breaks = c("Benzon", "Field"),
                        labels = c("Susceptible", "MD"),
                        values = c("#56B4E9", "#F0E442")) +
  annotate(geom = "segment", x = 145.6, y = 0.02, xend = 145.6, yend = 0.01, arrow = arrow(length = unit(2, "mm")))

S6panelA

#ggsave(file = "~/Desktop/S6panelA.png", S6panelA)
```


```{r}
S6panelB <- F0_growth_DD %>%
  filter(diet_strain == "O", end_weight_mg != "") %>%
  ggplot(aes(x = end_weight_mg, fill = field)) +
  geom_density(alpha = 0.6) +
  labs(x = "Weight (mg)", y = "Density", tag = "B") +
  scale_fill_manual(name = "Population",
                         breaks = c("Benzon", "Field"),
                          labels = c("Susceptible", "MD"),
                         values = c("#56B4E9", "#F0E442")) +
   annotate(geom = "segment", x = 129.5, y = 0.05, xend = 129.5, yend = 0.01, 
  arrow = arrow(length = unit(2, "mm")))

S6panelB

#ggsave(file = "~/Desktop/S6panelB.png", S6panelB)
```


```{r}
S6panelC <- F0_growth_CL %>%
  filter(diet_strain == "P", end_weight_mg != "") %>%
  ggplot(aes(x = end_weight_mg, fill = field)) +
  geom_density(alpha = 0.5) +
  labs(x = "Weight (mg)", y = "Density", tag = "C") +
  scale_fill_manual(name="Population",
                         breaks = c("Benzon", "Field"),
                          labels = c("Susceptible", "MD"),
                         values = c("#56B4E9", "#F0E442"))

S6panelC 

#ggsave(file = "~/Desktop/S6panelC.png", S6panelC)
```

```{r}
S6panelD <- F0_growth_CL %>%
  filter(diet_strain == "O", end_weight_mg != "") %>%
  ggplot(aes(x = end_weight_mg, fill = field)) +
  geom_density(alpha = 0.5) +
  labs(x = "Weight (mg)", y = "Density", tag = "D") +
  scale_fill_manual(name="Population",
                         breaks = c("Benzon", "Field"),
                          labels = c("Susceptible", "MD"),
                         values = c("#56B4E9", "#F0E442"))
S6panelD

#ggsave(file = "~/Desktop/S6panelD.png", S6panelD)
```

```{r}
S7panelA <- BAP11A1 %>%
  filter(end_weight_mg != "") %>%
  ggplot(aes(x = end_weight_mg, fill = Treatment)) +
  geom_density(alpha = 0.5) +
  labs(x = "Weight (mg)", y = "Density", tag= "A") +
  scale_fill_manual(name="Treatment",
                         breaks = c("DD", "CL"),
                          labels = c("Cry1Ab", "Control"),
                         values = c("#D55E00", "#0072B2"))

S7panelA
#ggsave(file = "~/Desktop/S7panelA.png", S7panelA)
```

```{r}
S7panelB <- DEO9A1 %>%
  filter(end_weight_mg != "") %>%
  ggplot(aes(x = end_weight_mg, fill = Treatment)) +
  geom_density(alpha = 0.5) +
  labs(x = "Weight (mg)", y = "Density", tag= "B") +
  scale_fill_manual(name="Treatment",
                         breaks = c("DD", "CL"),
                          labels = c("Cry1Ab", "Control"),
                         values = c("#D55E00", "#0072B2"))
S7panelB

#ggsave(file = "~/Desktop/S7panelB.png", S7panelB)
```