
```{r}
library(tidyverse)
library(gridExtra)
library(grid)
theme_set(theme_bw(base_size=10))
theme_update(panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  legend.position = "none")
```

# QTL power analysis

## Sample size and smallest detectable QTL
This function is one of the scripts provided with "Statistical power in genome-wide association studies and quantitative trait locus mapping" by Meiyue Wang and Shizhong Xu (2019)

```{r}
sample_1<-function(h2,lambda,rho=0.5,power=0.80,m=6756,alpha=70){ 
   alpha<-alpha/m
   y<-(qnorm(1-alpha/2)+qnorm(power))^2
   fn<-function(x,y){
      n0<-(x-1)/((1-rho)*lambda+1) + 1/((1+x*rho-rho)*lambda+1)
      f<-h2*(lambda+1)/(1-h2)*n0-y
      return(f)
   }
   myh2<-uniroot(f=fn,y=y,lower=0,upper=1e8)
   return(myh2$root)
}

sample_2<-function(h2,lambda,rho=0.5,power=0.80,m=6756,alpha=0.01){ 
   alpha<-alpha/m
   y<-(qnorm(1-alpha/2)+qnorm(power))^2
   fn<-function(x,y){
      n0<-(x-1)/((1-rho)*lambda+1) + 1/((1+x*rho-rho)*lambda+1)
      f<-h2*(lambda+1)/(1-h2)*n0-y
      return(f)
   }
   myh2<-uniroot(f=fn,y=y,lower=0,upper=1e8)
   return(myh2$root)
}


```


## Plug different values into the function and save the result

```{r}
test_values_1 <- list(0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55, 0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55, 0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55, 0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05)
test_values_2 <- list(0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33,
                      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                      3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3)

test_results <- list()

for (i in 1:length(test_values_1)){
  result <- sample_1(h2 = as.numeric(test_values_1[i]),lambda = as.numeric(test_values_2[i]))
  test_results <- c(test_results, result)
}

alpha_results_1 <- data.frame(cbind(unlist(test_values_1), unlist(test_values_2), unlist(test_results)))

test_results <- list()

for (i in 1:length(test_values_1)){
  result <- sample_2(h2 = as.numeric(test_values_1[i]),lambda = as.numeric(test_values_2[i]))
  test_results <- c(test_results, result)
}

alpha_results_2 <- data.frame(cbind(unlist(test_values_1), unlist(test_values_2), unlist(test_results)))
```

```{r}
cols <- c("0.33" = "red", "1" = "blue", "3" = "darkgreen")

no_correction <- ggplot(alpha_results_1, aes(y = as.numeric(X1), x = as.numeric(X3), color = as.factor(X2))) +
         geom_line(cex = 2, alpha = 0.5) +
  labs(y = "", x = "Sample size", color = "lambda", tag = "B") + theme(text=element_text(size=16))  +
  scale_color_manual(values = cols) +
  geom_vline(xintercept=68,linetype = "longdash") +
  geom_vline(xintercept=73,linetype = "longdash") +
  scale_y_continuous(breaks = seq(0, 1, by = .1)) +
  scale_x_continuous(limits = c(0, 200))

correction <- ggplot(alpha_results_2, aes(y = as.numeric(X1), x = as.numeric(X3), color = as.factor(X2))) +
         geom_line(cex = 2, alpha = 0.5) +
  labs(y = "Minimum detectable QTL", x = "Sample size", color = "lambda", tag = "A") + 
  theme(text=element_text(size=16))  +
  scale_color_manual(values = cols) +
  geom_vline(xintercept=68,linetype = "longdash") +
  geom_vline(xintercept=73,linetype = "longdash") +
  scale_y_continuous(breaks = seq(0, 1, by = .1)) +
  scale_x_continuous(limits = c(0, 200))

```

```{r}
jpeg("~/Desktop/UMD/Crosses_Analysis/Define_Windows/h2_samplesize_new3.jpg", width = 500, height = 300)

grid.arrange(correction, no_correction, ncol = 2, nrow = 1)
dev.off()
```
