

```{r}
library(tidyverse)
library(gridExtra)
library(grid)
theme_set(theme_bw(base_size=10))
theme_update(panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(), 
  plot.title = element_text(),
  panel.margin = unit(0, "lines"),
  strip.background = element_blank(),
  panel.border = element_blank(),
  legend.position = "none", 
  strip.text.x = element_text(margin = margin(0,0,0,0, "cm")))
```

```{r}
BAP11A1<- read.table("~/Desktop/UMD/Crosses_Analysis/VCF_files/BAP11A1.snps.vcf", header = FALSE)

DEO9A1<- read.table("~/Desktop/UMD/Crosses_Analysis/VCF_files/DEO9A1.snps.vcf", header = FALSE)

```

```{r}
BAP11A1_names<- read.table("~/Desktop/UMD/Crosses_Analysis/gemma/BAP11A1.snps.vcf", header = FALSE) %>% head(n=1)

DEO9A1_names<- read.table("~/Desktop/UMD/Crosses_Analysis/gemma/DEO9A1.snps.vcf", header = FALSE) %>% head(n=1)
```

```{r}
colnames(BAP11A1) <- BAP11A1_names
colnames(DEO9A1) <- DEO9A1_names
```

```{r}
BAP11A1_phenotypes <-  read.csv("~/Desktop/UMD/Crosses_Analysis/Raw_Data_Tabs_Crosses/tabs/BV_BA52_P11_BZM_A1_Scored.csv") %>%
  filter(Population != "BENZON") 

DEO9A1_phenotypes <- read.csv("~/Desktop/UMD/Crosses_Analysis/Raw_Data_Tabs_Crosses/tabs/BV_DE107_O9_BZM_A1_Scored.csv") %>%
  filter(Population != "Benzon")
```

 
```{r}
BAP11A1_bottom_150168_plot <- BAP11A1 %>%
  filter(CHROM == "KZ118301.1") %>%
filter(POS == "150168") %>%
  select(`1E25_BAP11A1`, `1G27_BAP11A1`, `1D39_BAP11A1`, `1E28_BAP11A1`, `1A28_BAP11A1`, `1A310_BAP11A1`, `1B312_BAP11A1`, `1D12_BAP11A1`, `1G310_BAP11A1`, `1B311_BAP11A1`) %>%
  gather() %>%
  separate(value, sep = ":", into = "genotype") %>%
  group_by(genotype) %>%
  summarize(n = n()) %>%
  filter(genotype != "./.") %>%
  ggplot(aes(x = genotype,y = n)) +
  geom_bar(stat="identity") +
  scale_x_discrete(limits = c("0/0", "0/1", "1/1")) +
  ylim(c(0,8)) +
  labs(y = "Number of individuals", x = "Genotype", tag = "C") +
  theme(text = element_text(size = 34)) 

BAP11A1_bottom_150168_plot 
```


```{r}
BAP11A1_top_150168_plot <- BAP11A1 %>%
  filter(CHROM == "KZ118301.1") %>%
  filter(POS == "150168") %>%
  select(`1A39_BAP11A1`, `1C312_BAP11A1`, `1A26_BAP11A1`, `1B12_BAP11A1`, `1C39_BAP11A1`, `1G14_BAP11A1`, `1D14_BAP11A1`, `1C26_BAP11A1`, `1C310_BAP11A1`, `1F14_BAP11A1`, `1C12_BAP11A1`,`1G25_BAP11A1` , `1D310_BAP11A1`, `1G11_BAP11A1`, `1F310_BAP11A1` ) %>%
  gather() %>%
  separate(value, sep = ":", into = "genotype") %>%
  group_by(genotype) %>%
  summarize(n = n()) %>%
  filter(genotype != "./.") %>%
  ggplot(aes(x = genotype,y = n)) +
  geom_bar(stat="identity") +
  scale_x_discrete(limits = c( "0/0", "0/1", "1/1")) +
  ylim(c(0,8)) +
  labs(y = "Number of individuals", x = "", tag = "A")+
  theme(text = element_text(size = 34)) 
 
BAP11A1_top_150168_plot 
```


```{r}
DEO9A1_top_150168_plot <- DEO9A1 %>%
  filter(CHROM == "KZ118301.1") %>%
  filter(POS == "150168") %>%
  select(`3A26`, `1C39`, `1D27`, `1B28`, `1A25`, `3C26`, `1D25`, `3D27`, `3B27`, `3B25`, `1D311`, `3C11`) %>%
  gather() %>%
  separate(value, sep = ":", into = "genotype") %>%
  group_by(genotype) %>%
  summarize(n = n()) %>%
  filter(genotype != "./.") %>%
  ggplot(aes(x = genotype,y = n)) +
  geom_bar(stat="identity") +
  scale_x_discrete(limits = c("0/0", "0/1", "1/1")) +
  ylim(c(0,8)) +
  labs(y = "", x = "", , tag = "B") +
  theme(text = element_text(size = 34)) 

DEO9A1_top_150168_plot
```


```{r}
DEO9A1_bottom_150168_plot <- DEO9A1 %>%
 filter(CHROM == "KZ118301.1") %>%
  filter(POS == "150168") %>%
  select(`1D312`, `1D310`, `3A13`, `3B13`, `1D14`, `1C11`, `3A12`, `3D28`, `1B12`, `3C25`) %>%
  gather() %>%
  separate(value, sep = ":", into = "genotype") %>%
  group_by(genotype) %>%
  summarize(n = n()) %>%
   filter(genotype != "./.") %>%
  ggplot(aes(x = genotype,y = n)) +
  geom_bar(stat="identity") +
  scale_x_discrete(limits = c( "0/0", "0/1", "1/1")) +
  ylim(c(0,8)) +
  labs(y = "", x = "Genotype", tag = "D")+
  theme(text = element_text(size = 34)) 

DEO9A1_bottom_150168_plot 
```




```{r}
jpeg("~/Desktop/UMD/Crosses_Analysis/Ref_allele/SNP_150168_plot.jpg", width = 1000, height = 1000)

grid.arrange(BAP11A1_top_150168_plot, DEO9A1_top_150168_plot ,BAP11A1_bottom_150168_plot, DEO9A1_bottom_150168_plot )

dev.off()
```
